{{ config(
  materialized='incremental',
  unique_key='"id"'
) }}

SELECT
	  "id"
    ,"key"
    ,"status_category_change_date"
    ,"issue_type_id"
    ,"issue_type_name"
    ,"time_spent"
    ,"project_key"
    ,"fix_versions"
    ,"aggregate_time_spent"
    ,"resolution"
    ,"resolution_date"
    ,"work_ratio"
    ,"last_viewed"
    ,"created"
    ,"priority_id"
    ,"priority_name"
    ,"labels"
    ,"time_estimate"
    ,"aggregate_time_original_estimate"
    ,"assignee_account_id"
    ,"assignee_display_name"
    ,"updated"
    ,"status_id"
    ,"status_name"
    ,"components"
    ,"time_original_estimate"
    ,"security"
    ,"aggregate_time_estimate"
    ,"summary"
    ,"description"
    ,"creator_account_id"
    ,"creator_email_address"
    ,"creator_display_name"
    ,"parent_id"
    ,"subtasks"
    ,"reporter_account_id"
    ,"reporter_display_name"
    ,"aggregate_progress"
    ,"aggregate_progress_total"
    ,"environment"
    ,"due_date"
    ,"progress"
    ,"progress_total"
    ,"custom_fields"
    ,CURRENT_DATE() AS "snapshot_date"
FROM {{ source('"WORKSPACE_7938092"', '"issues"') }}